server:
  port: 8000
  
#db configuration for mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin@123
    
#create, update, create-drop, validate
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true   
    
#file related all configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#smtp gmail configuration
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: someswarroy95@gmail.com
#    password: vciffbsqfhjfxqny
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
      
project:
  image: images/   
           